# Generated by Django 5.0.6 on 2024-06-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('Number', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('country', models.CharField(max_length=80)),
            ],
        ),
    ]
