# Generated by Django 5.0.6 on 2024-06-01 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manunited', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='Manunited',
        ),
    ]
