# Generated by Django 4.2.13 on 2024-06-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manunited', '0002_rename_post_manunited'),
    ]

    operations = [
        migrations.AddField(
            model_name='manunited',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
